domain: sandbox
descriptors:
- key: generic_key
  value: external
  rate_limit:
    unit: MINUTE
    requests_per_unit: 1
  descriptors:
  - key: header_match
    value: get_request
    rate_limit:
      unit: MINUTE
      requests_per_unit: 1